/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <stdio.h>
/* Header for class com_feb_ndkday1_SignTools */

#ifndef _Included_com_feb_ndkday1_SignTools
#define _Included_com_feb_ndkday1_SignTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_feb_ndkday1_SignTools
 * Method:    getSign
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_feb_ndkday1_SignTools_getSign
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
extern "C"
JNIEXPORT void JNICALL
Java_com_feb_ndkday1_SignTools_changeName(JNIEnv *, jobject);
extern "C"
JNIEXPORT void JNICALL
Java_com_feb_ndkday1_SignTools_add(JNIEnv *, jobject);